### PR TITLE
Add Russian Language

### PR DESCRIPTION
**Pull request by CoderCoV**

### CODE REVIEW

**Comment by kurotu** [comment]
@CoderCoV I'm not sure whether this PR is WIP, can I review? And I'd glad to hear about your motivation to disable notifications (validations).

**Comment by kurotu** [comment]
And if possible, please separate to two PRs for each feature, i18n and the button.

**Comment by CoderCoV** [comment]
> And if possible, please separate to two PRs for each feature, i18n and the button.

I'm new to Github and I don't really understand how to do this.

**Comment by CoderCoV** [comment]
> @CoderCoV I'm not sure whether this PR is WIP, can I review? And I'd glad to hear about your motivation to disable notifications (validations).

yes, you can see, this is a ready-made modification. 
My motivation is that notifications are at times annoying

**Comment by kurotu** [comment]
> And if possible, please separate to two PRs for each feature, i18n and the button.

Just create git branches for each feature from the master branch (It’s basic usage of git). I think i18n is ready to merge, but the disable button needs more discussion. Creating separated branches helps such situation.

> My motivation is that notifications are at times annoying

Usually the notification panel shows important info to properly build avatars. In other words, they doesn’t appear when the avatar is properly created. What message do you often see?

**Comment by CoderCoV** [comment]
> > And if possible, please separate to two PRs for each feature, i18n and the button.
> 
> Just create git branches for each feature from the master branch (It’s basic usage of git). I think i18n is ready to merge, but the disable button needs more discussion. Creating separated branches helps such situation.
> 
> > My motivation is that notifications are at times annoying
> 
> Usually the notification panel shows important info to properly build avatars. In other words, they doesn’t appear when the avatar is properly created. What message do you often see?

Honestly, I used to be very annoyed by notifications, although everything was fine with the avatar.
now I have looked at the code of the validation rules and everything is fine, I think the button is no longer needed.
I have deleted the changes related to the button.

**Comment by kurotu** [comment]
Got it. Feel free to let me know if validations are not good for your avatars in future.

By the way, the latest master branch makes some changes. Would you follow these? (Just leaving as a comment is also okay.)

### Added
```cs
internal override string NdmfPhaseLabel => "NDMF Phase to Convert";
internal override string NdmfPhaseTooltip => "Convert the avatar in the selected NDMF phase.";
```

### Changed
```patch
-        internal override string NetworkIDAssignerEditorDescription => "Assign Network IDs to the avatar's components such as PhysBones. IDs are determined by hash values of hierarchy paths from the avatar root.";
+        internal override string NetworkIDAssignerEditorDescription => "Assign Network IDs to the avatar's components such as PhysBones in build process. IDs are determined by hash values of hierarchy paths from the avatar root.";
```

**Comment by CoderCoV** [comment]
> Finally, the latest master branch makes some changes. Would you follow these? (Just leaving as a comment is also okay.)
Yes, of course.

**Comment by kurotu** [comment]
Sorry, my previous comment wat not enough. Would you translate also added/modified sentences?

**Comment by CoderCoV** [comment]
That's done, and the DMF has been translated too

**Comment by kurotu** [comment]
Thanks! I missed NDMF part.

And what about this part? "in build process" was added to the first sentence of `NetworkIDAssignerEditorDescription`.

```patch
- internal override string NetworkIDAssignerEditorDescription => "Assign Network IDs to the avatar's components such as PhysBones. IDs are determined by hash values of hierarchy paths from the avatar root.";
+ internal override string NetworkIDAssignerEditorDescription => "Assign Network IDs to the avatar's components such as PhysBones in build process. IDs are determined by hash values of hierarchy paths from the avatar root.";
```

**Comment by CoderCoV** [comment]
Yes, I changed that too.

**Comment by kurotu** [comment]
Thank you for your cooperation.

**Pull request merged**
